### ISSUE TITLE
[M4] Initiate a package review request

### ISSUE THREAD

**Issue by netsgnut** [UBC-MDS/bmi-calculator-r#42]

**Comment by netsgnut** [comment]
So we can review the license of F(L)OSS, based on some comprehensive list here: [Choose a License](https://choosealicense.com/licenses/) and [https://opensource.org/licenses/category](https://opensource.org/licenses/category).

(Disclaimer: I am not a lawyer, and the text below should not be treated as legal advice of any sort.)

Some of the questions that we probably want to think about are:
- Do we want to release this license in a "free (libre) and open source" license? If so, we have to allow non-commercial use (so [CC BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/) will be out of the list, but other CC licenses could still be used.
- Do we want to release our software in a slightly more restricted way? For example, GNU licenses like the GPL, LGPL, or AGPL have clauses to make sure the modifications made to the software should be released in the same license. The "SA" (ShareAlike) family of the Creative Commons license is also in the same spirit.
- Do we need to have clauses to waive trademark use? If so, we probably have to consider [MPL](https://opensource.org/licenses/MPL-2.0) and/or [Apache License 2.0](https://opensource.org/licenses/Apache-2.0).

The current license we opt for is a pretty permissive license (MIT license), which mandates that the copyright and software license text be preserved. It allows packaging into other software packages in other source code licenses and is considered compatible with many F(L)OSS licenses like GPL and MPL.

What do you think?

**Comment by qurat-azim** [comment]
done here: https://github.com/UBC-MDS/software-review-2023/issues/35
